name: build

on: 
  push: 
    branches: ["main"]

jobs:
  my-job:
    name: build-app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: oven-sh/setup-bun@v1

      - name: Install dependencies and build
      - run: |
          sudo apt-get install protobuf-compiler
          cd ./app
          bun install
          bun run wasm
          bun run build

      - name: Clean and deploy to another branch
        run: |
          git config user.name "lnxdxtf-action"
          git config user.email "gabrielramosmichaliszen@gmail.com"

          # Checkout the target branch, create it if it doesn't exist yet
          git fetch
          git checkout app/dist || git checkout -b app/dist
          git reset --hard origin/main  # Reset to the state of main (or another branch you want)
          git rm -rf .  # Remove all old files
          git commit -m "Clean app/dist" || echo "No changes to commit"
          git push origin app/dist

          # Copy dist folder content to root directory
          cp -r ./app/dist/* .  
          
          git add .
          git commit -m "Deploying dist folder"
          git push -u origin app/dist