  name: build

  on: 
    push: 
      branches: ["main"]

  jobs:
    my-job:
      name: build-app
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        
        - uses: oven-sh/setup-bun@v1
        
        - name: Install dependencies and build
          run: |
            sudo apt-get install protobuf-compiler
            cd ./app
            bun install
            bun run wasm
            bun run build
            
        - name: Clean target branch
          run: |
            git checkout ghpages
            git reset --hard origin/ghpages
            git clean -f -d

        - name: Copy dist folder to target branch
          run: |
            git checkout ghpages
            cp -r /app/dist/* .

        - name: Commit changes and push to target branch
          run: |
            git add .
            git commit -m "Deploy dist folder"
            git push origin ghpages
